# version: "3.2"
# services:
#   express-app:
#     build: .
#     ports:
#       - "3600:3600"
#     depends_on:
#       - db
#   db:
#     image: mongo:latest
#     hostname: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./data:/data/db


version: "3.2"
services:
  express-app:
    build: .
    ports:
      - "3600:3600"
    links:
      - db
  db:
    image: mongo:latest
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=myKrew
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
